name: CosmicCapital
version: '1.2'
main: me.antritus.astral.cosmiccapital.CosmicCapital
api-version: '1.13'
description: "Economy manager for Astral servers. This is the core of all economy."

loadbefore:
  - Auctionverse
